CREATE DATABASE SENAI_PERSONAGENS_WEBAPI_MANHA

USE SENAI_PERSONAGENS_WEBAPI_MANHA

CREATE TABLE PERSONAGENS(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(250) NOT NULL,
	LANCAMENTO VARCHAR(250) NOT NULL
);

INSERT INTO PERSONAGENS
VALUES('Homem-Aranha', 'Amazing Fantasy #15 (1962)'),
		('O Incrível Hulk', 'O Incrível Hulk #1 (1962)'),
		('Homem de Ferro', 'Tales of Suspense #39 (1963)')

SELECT * FROM PERSONAGENS